### ISSUE TITLE
Search bar on landing page isn't "bootstrappy"

### ISSUE THREAD

**Issue by rethore** [FractalFlows/Emergence#14]
Somehow the corners are both round and square at the same time.
<img width="494" alt="screen shot 2016-04-19 at 10 19 20" src="https://cloud.githubusercontent.com/assets/2746159/14632300/380d1e14-0618-11e6-9cd2-591930694856.png">

**Comment by FFemergence** [comment]
yeah that's true.

**Comment by FFemergence** [comment]
I will have a look at it.

**Comment by IAbda** [comment]
fixed.

**Comment by rethore** [comment]
Awesome, feel free to make a pull request when you are ready.

**Comment by IAbda** [comment]
awesome
