### ISSUE TITLE
Figures and Diagrams for features

### ISSUE THREAD

**Issue by IAbda** [FractalFlows/Emergence#22]
we need to provide some representative figures and diagrams to accompany the text describing various features of Emergence.

Four Diagrams to start with:
- Register relationships on the Blockchain
- External Integrations
- Incentives and reputations through smart contracts
- Track knowledge bits

**Comment by IAbda** [comment]
A new pull request is made that includes all the above mentioned graphics in this issue.

**Comment by rethore** [comment]
Fixed by #24
