### ISSUE TITLE
Once clicked the links in the search do not work

### ISSUE THREAD

**Issue by rethore** [FractalFlows/Emergence#43]
Once one has clicked on a link in the search box, the keywords stay in the search box. If you click on the search box again, you get the previous search results but they have become inactive, when you click on it it doesn't lead you anywhere.

Solution:
- Remove the search context from the search box once the user has clicked on it
- Somehow reactivate the links after they have been used

**Comment by grsabreu** [comment]
Thanks for finding out this bug, @rethore. However, I wasn't able to reproduce it.
Which keywords did you tried to search for?

**Comment by rethore** [comment]
I used the search term "topfarm", then clicked on the first link. When I'm back at home I'll make a screencast to show the bug. Maybe it's due to the browser I'm using?

**Comment by guilhermedecampo** [comment]
https://www.pivotaltracker.com/story/show/138917771
